"""add_audit_mixin_and_events

Revision ID: 01aa02d8cf05
Revises: 003_add_tenants
Create Date: 2026-02-08 23:30:05.272803
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '01aa02d8cf05'
down_revision: Union[str, None] = '003_add_tenants'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create audit_events table
    op.create_table(
        'audit_events',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resource_id', sa.String(500), nullable=False, index=True),
        sa.Column('resource_type', sa.String(100), nullable=False, index=True),
        sa.Column('resource_name', sa.String(255), nullable=False, index=True),
        sa.Column('action', sa.String(20), nullable=False, index=True),
        sa.Column('actor_id', sa.String(255), nullable=True, index=True),
        sa.Column('actor_type', sa.String(50), nullable=False, server_default='SYSTEM'),
        sa.Column('actor_display_name', sa.String(255), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, index=True),
        sa.Column('previous_state', postgresql.JSONB(), nullable=True),
        sa.Column('new_state', postgresql.JSONB(), nullable=True),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('correlation_id', sa.String(36), nullable=True, index=True),
        sa.Column('request_id', sa.String(36), nullable=True, index=True),
        sa.Column('source_ip', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.String(500), nullable=True),
        sa.Column('extra_data', postgresql.JSONB(), nullable=True),
    )
    
    # Composite indexes for common query patterns
    op.create_index('idx_audit_resource_action', 'audit_events', ['resource_id', 'action'])
    op.create_index('idx_audit_actor_time', 'audit_events', ['actor_id', 'timestamp'])
    op.create_index('idx_audit_type_action_time', 'audit_events', ['resource_type', 'action', 'timestamp'])
    
    # Add AuditMixin columns to all resource tables
    # Note: last_action has server_default='CREATE' for existing rows
    op.add_column('deployments', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('deployments', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('deployments', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('deployments', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_deployments_created_by'), 'deployments', ['created_by'], unique=False)
    op.create_index(op.f('ix_deployments_updated_by'), 'deployments', ['updated_by'], unique=False)
    op.add_column('extended_locations', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('extended_locations', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('extended_locations', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('extended_locations', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_extended_locations_created_by'), 'extended_locations', ['created_by'], unique=False)
    op.create_index(op.f('ix_extended_locations_updated_by'), 'extended_locations', ['updated_by'], unique=False)
    op.add_column('locations', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('locations', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_locations_created_by'), 'locations', ['created_by'], unique=False)
    op.create_index(op.f('ix_locations_updated_by'), 'locations', ['updated_by'], unique=False)
    op.add_column('management_groups', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('management_groups', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('management_groups', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('management_groups', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_management_groups_created_by'), 'management_groups', ['created_by'], unique=False)
    op.create_index(op.f('ix_management_groups_updated_by'), 'management_groups', ['updated_by'], unique=False)
    op.add_column('policies', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('policies', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('policies', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('policies', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_policies_created_by'), 'policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_policies_updated_by'), 'policies', ['updated_by'], unique=False)
    op.add_column('resource_groups', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('resource_groups', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('resource_groups', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('resource_groups', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_resource_groups_created_by'), 'resource_groups', ['created_by'], unique=False)
    op.create_index(op.f('ix_resource_groups_updated_by'), 'resource_groups', ['updated_by'], unique=False)
    op.add_column('subscriptions', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('subscriptions', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_subscriptions_created_by'), 'subscriptions', ['created_by'], unique=False)
    op.create_index(op.f('ix_subscriptions_updated_by'), 'subscriptions', ['updated_by'], unique=False)
    op.add_column('tags', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('tags', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('tags', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('tags', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tags_created_by'), 'tags', ['created_by'], unique=False)
    op.create_index(op.f('ix_tags_updated_by'), 'tags', ['updated_by'], unique=False)
    op.add_column('tenants', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('last_action', sa.String(length=20), server_default='CREATE', nullable=False))
    op.add_column('tenants', sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tenants_created_by'), 'tenants', ['created_by'], unique=False)
    op.create_index(op.f('ix_tenants_updated_by'), 'tenants', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_updated_by'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_by'), table_name='tenants')
    op.drop_column('tenants', 'last_action_at')
    op.drop_column('tenants', 'last_action')
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'created_by')
    op.drop_index(op.f('ix_tags_updated_by'), table_name='tags')
    op.drop_index(op.f('ix_tags_created_by'), table_name='tags')
    op.drop_column('tags', 'last_action_at')
    op.drop_column('tags', 'last_action')
    op.drop_column('tags', 'updated_by')
    op.drop_column('tags', 'created_by')
    op.drop_index(op.f('ix_subscriptions_updated_by'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_by'), table_name='subscriptions')
    op.drop_column('subscriptions', 'last_action_at')
    op.drop_column('subscriptions', 'last_action')
    op.drop_column('subscriptions', 'updated_by')
    op.drop_column('subscriptions', 'created_by')
    op.drop_index(op.f('ix_resource_groups_updated_by'), table_name='resource_groups')
    op.drop_index(op.f('ix_resource_groups_created_by'), table_name='resource_groups')
    op.drop_column('resource_groups', 'last_action_at')
    op.drop_column('resource_groups', 'last_action')
    op.drop_column('resource_groups', 'updated_by')
    op.drop_column('resource_groups', 'created_by')
    op.drop_index(op.f('ix_policies_updated_by'), table_name='policies')
    op.drop_index(op.f('ix_policies_created_by'), table_name='policies')
    op.drop_column('policies', 'last_action_at')
    op.drop_column('policies', 'last_action')
    op.drop_column('policies', 'updated_by')
    op.drop_column('policies', 'created_by')
    op.drop_index(op.f('ix_management_groups_updated_by'), table_name='management_groups')
    op.drop_index(op.f('ix_management_groups_created_by'), table_name='management_groups')
    op.drop_column('management_groups', 'last_action_at')
    op.drop_column('management_groups', 'last_action')
    op.drop_column('management_groups', 'updated_by')
    op.drop_column('management_groups', 'created_by')
    op.drop_index(op.f('ix_locations_updated_by'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_by'), table_name='locations')
    op.drop_column('locations', 'last_action_at')
    op.drop_column('locations', 'last_action')
    op.drop_column('locations', 'updated_by')
    op.drop_column('locations', 'created_by')
    op.drop_index(op.f('ix_extended_locations_updated_by'), table_name='extended_locations')
    op.drop_index(op.f('ix_extended_locations_created_by'), table_name='extended_locations')
    op.drop_column('extended_locations', 'last_action_at')
    op.drop_column('extended_locations', 'last_action')
    op.drop_column('extended_locations', 'updated_by')
    op.drop_column('extended_locations', 'created_by')
    op.drop_index(op.f('ix_deployments_updated_by'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_by'), table_name='deployments')
    op.drop_column('deployments', 'last_action_at')
    op.drop_column('deployments', 'last_action')
    op.drop_column('deployments', 'updated_by')
    op.drop_column('deployments', 'created_by')
    
    # Drop audit_events table
    op.drop_index('idx_audit_type_action_time', table_name='audit_events')
    op.drop_index('idx_audit_actor_time', table_name='audit_events')
    op.drop_index('idx_audit_resource_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
