"""Subscription request models."""
from typing import Dict, Optional
from pydantic import Field

from itl_controlplane_sdk.core.models.base import CoreBaseModel
from itl_controlplane_sdk.core.models.subscriptions.properties import SubscriptionProperties


class CreateSubscriptionRequest(CoreBaseModel):
    """Create Subscription request — subscription_id is auto-generated by the server."""
    resource_name: str = Field(..., min_length=1, max_length=260, description="Resource name")
    subscription_id: Optional[str] = Field(None, description="Subscription ID (optional, server will generate if not provided)")
    resource_group: str = Field(..., description="Resource Group")
    resource_type: str = Field(..., description="Resource type")
    location: str = Field(..., description="Location")
    display_name: str = Field(..., description="Display name for the subscription")
    state: Optional[str] = Field("Enabled", description="Subscription state")
    tags: Optional[Dict[str, str]] = Field(None, description="Subscription tags")
    properties: Optional[SubscriptionProperties] = Field(None, description="Subscription properties")
