"""
Bicep renderer.

Outputs:
  - main.bicep                    : Root module with all resources
  - policies/<name>.bicep         : One Bicep file per Azure policy
  - modules/<resource>.bicep      : One Bicep module per resource type

Bicep is Azure-native; Kubernetes/Talos platforms fall back to a note.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

from .base import (
    ComponentType,
    IaCRenderer,
    Platform,
    RenderContext,
    RenderOutput,
    RendererType,
)


class BicepRenderer(IaCRenderer):
    """Renders policy and resource specs to Azure Bicep files."""

    renderer_type = RendererType.BICEP

    def render(self, ctx: RenderContext) -> RenderOutput:
        files: Dict[str, str] = {}
        policy_count = 0
        resource_count = 0

        if ctx.component_type in (ComponentType.POLICY, ComponentType.ALL):
            if ctx.platform == Platform.AZURE:
                policy_files, count = self._render_policies(ctx)
                files.update(policy_files)
                policy_count = count
            else:
                files["note.txt"] = (
                    "# Bicep renderer is Azure-only.\n"
                    "# Use Terraform or Pulumi for Kubernetes/Talos policies.\n"
                )

        if ctx.component_type in (ComponentType.RESOURCE, ComponentType.ALL):
            if ctx.platform == Platform.AZURE:
                resource_files, count = self._render_resources(ctx)
                files.update(resource_files)
                resource_count = count

        # Emit a main.bicep that references all module files
        if files and ctx.platform == Platform.AZURE:
            files["main.bicep"] = self._render_main(ctx, files)

        return RenderOutput(
            files=files,
            renderer_type=RendererType.BICEP,
            platform=ctx.platform,
            policy_count=policy_count,
            resource_count=resource_count,
        )

    # ------------------------------------------------------------------
    # Policies
    # ------------------------------------------------------------------

    def _render_policies(self, ctx: RenderContext) -> tuple[Dict[str, str], int]:
        files: Dict[str, str] = {}
        for policy in ctx.policies:
            name = policy.get("name", "policy")
            safe = self._safe_name(name)
            props = policy.get("properties", policy)
            bicep = self._policy_to_bicep(safe, props, ctx)
            files[f"policies/{safe}.bicep"] = bicep
        return files, len(ctx.policies)

    def _policy_to_bicep(
        self, safe_name: str, props: Dict[str, Any], ctx: RenderContext
    ) -> str:
        display_name = props.get("displayName", safe_name)
        description = props.get("description", "")
        mode = props.get("mode", "All")
        policy_rule = json.dumps(props.get("policyRule", {}), indent=2)
        parameters = json.dumps(props.get("parameters", {}), indent=2)
        profile_tag = f"\n  'profile': '{ctx.profile_name}'" if ctx.profile_name else ""

        return f"""\
// Policy: {display_name}
// Generated by ITL IaC Renderer (Bicep)

targetScope = 'subscription'

resource policyDef_{safe_name.replace("-", "_")} 'Microsoft.Authorization/policyDefinitions@2021-06-01' = {{
  name: '{safe_name}'
  properties: {{
    displayName: '{display_name}'
    description: '{description}'
    policyType: 'Custom'
    mode: '{mode}'
    metadata: {{
      'managed-by': 'itl-iac'{profile_tag}
    }}
    parameters: {parameters}
    policyRule: {policy_rule}
  }}
}}
"""

    # ------------------------------------------------------------------
    # Resources
    # ------------------------------------------------------------------

    def _render_resources(self, ctx: RenderContext) -> tuple[Dict[str, str], int]:
        files: Dict[str, str] = {}
        tags = self._default_tags(ctx)
        for spec in ctx.resources:
            safe = self._safe_name(spec.get("name", "resource"))
            bicep = self._resource_to_bicep(spec, ctx.location, tags)
            if bicep:
                files[f"modules/{safe}.bicep"] = bicep
        return files, len(files)

    def _resource_to_bicep(
        self,
        spec: Dict[str, Any],
        location: str,
        tags: Dict[str, str],
    ) -> str | None:
        res_type = spec.get("type", "").lower()
        name = spec.get("name", "resource")
        safe = self._safe_name(name)
        props = spec.get("properties", {})
        tags_str = self._bicep_tags(tags)

        _TEMPLATES: Dict[str, str] = {
            "azure/keyvault": self._keyvault_bicep,
            "azure/aks": self._aks_bicep,
            "azure/nsg": self._nsg_bicep,
            "azure/vnet": self._vnet_bicep,
            "azure/storage": self._storage_bicep,
            "azure/identity": self._identity_bicep,
        }

        fn = _TEMPLATES.get(res_type)
        return fn(safe, name, location, props, tags_str) if fn else None

    # ------ per-resource Bicep snippets ------

    def _keyvault_bicep(self, safe: str, name: str, loc: str, props: Dict, tags: str) -> str:
        sku = props.get("sku", {}).get("name", "standard")
        return f"""\
// KeyVault: {name}
param location string = '{loc}'

resource kv_{safe.replace("-", "_")} 'Microsoft.KeyVault/vaults@2023-07-01' = {{
  name: '{name}'
  location: location
  tags: {tags}
  properties: {{
    sku: {{ name: '{sku}', family: 'A' }}
    tenantId: subscription().tenantId
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    enableRbacAuthorization: true
  }}
}}
"""

    def _aks_bicep(self, safe: str, name: str, loc: str, props: Dict, tags: str) -> str:
        node_count = props.get("agentPoolProfiles", [{}])[0].get("count", 3)
        vm_size = props.get("agentPoolProfiles", [{}])[0].get("vmSize", "Standard_D4s_v3")
        return f"""\
// AKS Cluster: {name}
param location string = '{loc}'

resource aks_{safe.replace("-", "_")} 'Microsoft.ContainerService/managedClusters@2024-02-01' = {{
  name: '{name}'
  location: location
  tags: {tags}
  identity: {{ type: 'SystemAssigned' }}
  properties: {{
    dnsPrefix: '{name}'
    enableRBAC: true
    agentPoolProfiles: [
      {{
        name: 'system'
        count: {node_count}
        vmSize: '{vm_size}'
        mode: 'System'
        osDiskSizeGB: 128
      }}
    ]
    networkProfile: {{ networkPlugin: 'azure', networkPolicy: 'azure' }}
  }}
}}
"""

    def _nsg_bicep(self, safe: str, name: str, loc: str, props: Dict, tags: str) -> str:
        return f"""\
// NSG: {name}
param location string = '{loc}'

resource nsg_{safe.replace("-", "_")} 'Microsoft.Network/networkSecurityGroups@2023-09-01' = {{
  name: '{name}'
  location: location
  tags: {tags}
  properties: {{
    securityRules: []
  }}
}}
"""

    def _vnet_bicep(self, safe: str, name: str, loc: str, props: Dict, tags: str) -> str:
        prefix = props.get("addressPrefix", "10.0.0.0/16")
        return f"""\
// VNet: {name}
param location string = '{loc}'

resource vnet_{safe.replace("-", "_")} 'Microsoft.Network/virtualNetworks@2023-09-01' = {{
  name: '{name}'
  location: location
  tags: {tags}
  properties: {{
    addressSpace: {{ addressPrefixes: ['{prefix}'] }}
  }}
}}
"""

    def _storage_bicep(self, safe: str, name: str, loc: str, props: Dict, tags: str) -> str:
        sku = props.get("sku", "Standard_LRS")
        return f"""\
// Storage: {name}
param location string = '{loc}'

resource storage_{safe.replace("-", "_")} 'Microsoft.Storage/storageAccounts@2023-01-01' = {{
  name: '{name}'
  location: location
  tags: {tags}
  kind: 'StorageV2'
  sku: {{ name: '{sku}' }}
  properties: {{
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
    allowBlobPublicAccess: false
  }}
}}
"""

    def _identity_bicep(self, safe: str, name: str, loc: str, props: Dict, tags: str) -> str:
        return f"""\
// Managed Identity: {name}
param location string = '{loc}'

resource id_{safe.replace("-", "_")} 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {{
  name: '{name}'
  location: location
  tags: {tags}
}}
"""

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def _render_main(self, ctx: RenderContext, files: Dict[str, str]) -> str:
        profile_comment = f" — profile: {ctx.profile_name}" if ctx.profile_name else ""
        modules: List[str] = []
        for fname in files:
            if fname.startswith("modules/") and fname.endswith(".bicep"):
                mod_name = fname[8:-6].replace("-", "_")
                modules.append(
                    f"module {mod_name} './{fname}' = {{\n"
                    f"  name: '{mod_name}-deploy'\n"
                    f"}}"
                )
        modules_block = "\n\n".join(modules) if modules else "// No resource modules"

        return f"""\
// ITL IaC — Bicep root template{profile_comment}
// Generated by ITL ControlPlane SDK

targetScope = 'resourceGroup'

param location string = '{ctx.location}'

{modules_block}
"""

    def _bicep_tags(self, tags: Dict[str, str]) -> str:
        inner = "\n  ".join(f"'{k}': '{v}'" for k, v in tags.items())
        return "{\n  " + inner + "\n}"
