"""
Terraform (HCL) renderer.

Outputs:
  - main.tf           : Provider config + all resources
  - policies.tf       : Policy resources (Azure or Kubernetes)
  - variables.tf      : Input variables
  - outputs.tf        : Output values

Supports:
  - Platform.AZURE      → azurerm provider
  - Platform.KUBERNETES → kubernetes provider (Kyverno ClusterPolicy as kubectl_manifest)
  - Platform.TALOS      → kubernetes provider (same as above)
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

from .base import (
    ComponentType,
    IaCRenderer,
    Platform,
    RenderContext,
    RenderOutput,
    RendererType,
)


class TerraformRenderer(IaCRenderer):
    """Renders policy and resource specs to Terraform HCL files."""

    renderer_type = RendererType.TERRAFORM

    def render(self, ctx: RenderContext) -> RenderOutput:
        files: Dict[str, str] = {}
        policy_count = 0
        resource_count = 0

        files["main.tf"] = self._render_main(ctx)
        files["variables.tf"] = self._render_variables(ctx)
        files["outputs.tf"] = self._render_outputs(ctx)

        if ctx.component_type in (ComponentType.POLICY, ComponentType.ALL):
            policies_tf, count = self._render_policies(ctx)
            files["policies.tf"] = policies_tf
            policy_count = count

        if ctx.component_type in (ComponentType.RESOURCE, ComponentType.ALL):
            resources_tf, count = self._render_resources(ctx)
            if resources_tf.strip():
                files["resources.tf"] = resources_tf
                resource_count = count

        return RenderOutput(
            files=files,
            renderer_type=RendererType.TERRAFORM,
            platform=ctx.platform,
            policy_count=policy_count,
            resource_count=resource_count,
        )

    # ------------------------------------------------------------------
    # Provider / main.tf
    # ------------------------------------------------------------------

    def _render_main(self, ctx: RenderContext) -> str:
        profile_comment = f" (profile: {ctx.profile_name})" if ctx.profile_name else ""
        if ctx.platform == Platform.AZURE:
            provider_block = """\
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
"""
        else:
            provider_block = """\
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.14"
    }
  }
}

provider "kubernetes" {
  config_path = var.kubeconfig_path
}

provider "kubectl" {
  config_path = var.kubeconfig_path
}
"""
        return f"""\
# ITL IaC — Terraform{profile_comment}
# Generated by ITL ControlPlane SDK

{provider_block}"""

    # ------------------------------------------------------------------
    # variables.tf
    # ------------------------------------------------------------------

    def _render_variables(self, ctx: RenderContext) -> str:
        vars_block = ""
        if ctx.platform == Platform.AZURE:
            vars_block = f"""\
variable "location" {{
  description = "Azure region"
  type        = string
  default     = "{ctx.location}"
}}

variable "stack_name" {{
  description = "Stack / environment name"
  type        = string
  default     = "{ctx.stack_name}"
}}
"""
        else:
            vars_block = f"""\
variable "kubeconfig_path" {{
  description = "Path to kubeconfig file"
  type        = string
  default     = "~/.kube/config"
}}

variable "namespace" {{
  description = "Kubernetes namespace"
  type        = string
  default     = "{ctx.namespace}"
}}
"""
        return vars_block

    # ------------------------------------------------------------------
    # outputs.tf
    # ------------------------------------------------------------------

    def _render_outputs(self, ctx: RenderContext) -> str:
        return """\
# Add output values for resources created in this stack
"""

    # ------------------------------------------------------------------
    # Policies
    # ------------------------------------------------------------------

    def _render_policies(self, ctx: RenderContext) -> tuple[str, int]:
        if not ctx.policies:
            return "# No policies defined\n", 0

        blocks: List[str] = []
        if ctx.platform == Platform.AZURE:
            for i, policy in enumerate(ctx.policies):
                blocks.append(self._azure_policy_hcl(policy, i))
        else:
            # Kubernetes / Talos: use kubectl_manifest for Kyverno ClusterPolicies
            for i, policy in enumerate(ctx.policies):
                blocks.append(self._kyverno_policy_hcl(policy, i))

        return "\n\n".join(blocks) + "\n", len(ctx.policies)

    def _azure_policy_hcl(self, policy: Dict[str, Any], idx: int) -> str:
        name = policy.get("name", f"policy-{idx}")
        safe = name.lower().replace("-", "_").replace(" ", "_")
        props = policy.get("properties", policy)
        display_name = props.get("displayName", name)
        description = props.get("description", "")
        mode = props.get("mode", "All")
        policy_rule = json.dumps(props.get("policyRule", {}))
        parameters = json.dumps(props.get("parameters", {}))

        return f"""\
resource "azurerm_policy_definition" "{safe}" {{
  name         = "{name}"
  policy_type  = "Custom"
  mode         = "{mode}"
  display_name = "{display_name}"
  description  = "{description}"

  policy_rule = jsonencode({policy_rule})
  parameters  = jsonencode({parameters})

  metadata = jsonencode({{
    "managed-by" = "itl-iac"
  }})
}}"""

    def _kyverno_policy_hcl(self, policy: Dict[str, Any], idx: int) -> str:
        name = policy.get("metadata", {}).get("name", f"policy-{idx}")
        safe = name.lower().replace("-", "_")
        manifest_json = json.dumps(policy, indent=2)

        return f"""\
resource "kubectl_manifest" "kyverno_{safe}" {{
  yaml_body = <<-YAML
{self._dict_to_yaml(policy)}
  YAML
}}"""

    def _dict_to_yaml(self, d: Dict[str, Any], indent: int = 0) -> str:
        """Minimal YAML-like serialiser for simple nested dicts/lists."""
        try:
            import yaml  # type: ignore
            return yaml.dump(d, default_flow_style=False, sort_keys=False)
        except ImportError:
            return json.dumps(d, indent=2)

    # ------------------------------------------------------------------
    # Resources
    # ------------------------------------------------------------------

    def _render_resources(self, ctx: RenderContext) -> tuple[str, int]:
        if not ctx.resources:
            return "", 0

        blocks: List[str] = []
        tags = self._default_tags(ctx)

        for spec in ctx.resources:
            block = self._resource_to_hcl(spec, ctx, tags)
            if block:
                blocks.append(block)

        return "\n\n".join(blocks) + "\n", len(blocks)

    def _resource_to_hcl(
        self,
        spec: Dict[str, Any],
        ctx: RenderContext,
        tags: Dict[str, str],
    ) -> str | None:
        res_type = spec.get("type", "").lower()
        name = spec.get("name", "resource")
        safe = name.lower().replace("-", "_")
        props = spec.get("properties", {})
        tags_merged = {**tags, **spec.get("tags", {})}
        tags_hcl = self._hcl_map(tags_merged)

        _MAP: Dict[str, Any] = {
            "azure/keyvault": self._keyvault_hcl,
            "azure/aks": self._aks_hcl,
            "azure/nsg": self._nsg_hcl,
            "azure/vnet": self._vnet_hcl,
            "azure/storage": self._storage_hcl,
            "azure/identity": self._identity_hcl,
        }

        fn = _MAP.get(res_type)
        return fn(safe, name, props, tags_hcl, ctx) if fn else None

    # ---- per-resource HCL blocks ----

    def _keyvault_hcl(self, safe, name, props, tags, ctx) -> str:
        sku = props.get("sku", {}).get("name", "standard")
        return f"""\
resource "azurerm_key_vault" "{safe}" {{
  name                = "{name}"
  location            = var.location
  resource_group_name = var.stack_name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "{sku}"
  soft_delete_retention_days = 90
  purge_protection_enabled   = true
  enable_rbac_authorization  = true
  tags = {tags}
}}"""

    def _aks_hcl(self, safe, name, props, tags, ctx) -> str:
        pool = props.get("agentPoolProfiles", [{}])[0]
        node_count = pool.get("count", 3)
        vm_size = pool.get("vmSize", "Standard_D4s_v3")
        return f"""\
resource "azurerm_kubernetes_cluster" "{safe}" {{
  name                = "{name}"
  location            = var.location
  resource_group_name = var.stack_name
  dns_prefix          = "{name}"

  default_node_pool {{
    name       = "system"
    node_count = {node_count}
    vm_size    = "{vm_size}"
  }}

  identity {{ type = "SystemAssigned" }}

  network_profile {{
    network_plugin = "azure"
    network_policy = "azure"
  }}

  tags = {tags}
}}"""

    def _nsg_hcl(self, safe, name, props, tags, ctx) -> str:
        return f"""\
resource "azurerm_network_security_group" "{safe}" {{
  name                = "{name}"
  location            = var.location
  resource_group_name = var.stack_name
  tags = {tags}
}}"""

    def _vnet_hcl(self, safe, name, props, tags, ctx) -> str:
        prefix = props.get("addressPrefix", "10.0.0.0/16")
        return f"""\
resource "azurerm_virtual_network" "{safe}" {{
  name                = "{name}"
  location            = var.location
  resource_group_name = var.stack_name
  address_space       = ["{prefix}"]
  tags = {tags}
}}"""

    def _storage_hcl(self, safe, name, props, tags, ctx) -> str:
        sku = props.get("sku", "Standard_LRS")
        return f"""\
resource "azurerm_storage_account" "{safe}" {{
  name                     = "{name}"
  resource_group_name      = var.stack_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
  enable_https_traffic_only = true
  tags = {tags}
}}"""

    def _identity_hcl(self, safe, name, props, tags, ctx) -> str:
        return f"""\
resource "azurerm_user_assigned_identity" "{safe}" {{
  name                = "{name}"
  location            = var.location
  resource_group_name = var.stack_name
  tags = {tags}
}}"""

    def _hcl_map(self, d: Dict[str, str]) -> str:
        inner = "\n    ".join(f'"{k}" = "{v}"' for k, v in d.items())
        return "{\n    " + inner + "\n  }"
